Nalypoll/Nalypoll/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('main.urls', namespace='main'))
    # path('admin/', admin.site.urls),
]

Nalypoll/apps/main/urls.py
from django.urls import path, include, re_path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('poll/<int:tweet_id>', views.poll, name='poll'),
    path('poll/register', views.register_poll, name='register_poll'), # POST
    path('poll/register/<int:tweet_id>', views.register_poll, name='register_poll'),
    path('poll/unregister/<int:tweet_id>', views.unregister_poll, name='unregister_poll'),
    path('poll/remove/<int:tweet_id>', views.remove_poll, name='remove_poll'),
    # path('update/<int:tweet_id>', views.update, name='update'),
    path('user', views.user, name='user'),
    path('user/recent', views.user_recent, name='user_recent'),
    path('user/menu', views.user_menu, name='user_menu'),
    path('user/menu/polls/remove', views.user_remove_polls, name='user_remove_polls'),
    path('user/menu/polls/unregister', views.user_unregister_polls, name='user_unregister_polls'),
    path('oauth', views.oauth, name='oauth'),
    path('oauth/callback', views.oauth_callback, name='oauth_callback'),
    path('oauth/remove', views.oauth_remove, name='oauth_remove'),
    path('oauth/logout', views.oauth_logout, name='oauth_logout'),
]

Nalypoll/templates/base.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

<title>{% block pagetitle %}{% endblock %}</title>

<meta property="og:title" content="Nalypoll - 投票ツイートグラフ追跡サービス">
<meta property="og:description" content="投票ツイートを登録すると投票状況を追跡してグラフ化します">
<meta property="og:type" content="website">
<meta property="og:url" content="https://nalypoll.aoirint.com">
<meta property="og:image" content="https://nalypoll.aoirint.com/static/images/ogp.png">

<link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
  crossorigin="anonymous">

<style>
@media (max-width: 992px) and (max-height: 500px) and (orientation: landscape) {
  .mobile-landscape-fill-height {
    width: 56.249vh;
    height: 100vh;
  }
}
</style>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
  crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"
  integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI="
  crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/blueimp-md5@2.17.0/js/md5.min.js"
  integrity="sha256-cpbDsuAF6YYKGsywuE65CvzsMKN6x4m6733ZnT3QHHE="
  crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/d3@5.16.0/dist/d3.min.js"
  integrity="sha256-Xb6SSzhH3wEPC4Vy3W70Lqh9Y3Du/3KxPqI2JHQSpTw="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/papaparse@5.3.0/papaparse.min.js"
  integrity="sha256-Xjq9HM9n3XzT47n/NmSEaJUwPi7hme++D8mxHfSr+0Q="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js"
  integrity="sha256-ur/YlHMU96MxHEsy3fHGszZHas7NzH4RQlD4tDVvFhw="
  crossorigin="anonymous"></script>
<script src="{% static 'js/barchartrace.js' %}"></script>

{% if NALYPOLL_GTAG %}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ NALYPOLL_GTAG }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ NALYPOLL_GTAG }}');
</script>
{% endif %}

<!-- https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/set-up-twitter-for-websites -->
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>


<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main:index' %}">Nalypoll</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
{% if twitter.is_authenticated %}
      <li class="nav-item">
        <a href="{% url 'main:user' %}" class="nav-link">マイページ</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'main:user_menu' %}" class="nav-link">メニュー</a>
      </li>
{% endif %}
    </ul>
    <ul class="navbar-nav">
{% if twitter.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">
        ログイン中（<a href="https://twitter.com/{{ twitter.screen_name }}" target="_blank">@{{ twitter.screen_name }}</a>）
        </span>
      </li>
      <li class="nav-item">
        <form method="POST" action="{% url 'main:oauth_logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn nav-link">ログアウト</button>
        </form>
      </li>
{% endif %}
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}
{% block main2 %}{% endblock %}

Nalypoll/templates/base_basic.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
{% block main %}{% endblock %}
</div>
{% endblock %}

Nalypoll/templates/base_fluid.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
{% block main %}{% endblock %}
</div>
{% endblock %}

Nalypoll/templates/index.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}Nalypoll - 投票ツイートグラフ追跡サービス{% endblock %}

{% block main %}
<h2 class="mt-4">Nalypoll</h2>

<p>
  <form method="POST" action="{% url 'main:oauth' %}">
    {% csrf_token %}
    <button type="submit" class="btn">
      <img src="{% static 'images/auth_twitter.png' %}" alt="Sign in with Twitter">
    </button>
  </form>

<hr>

<h3>【お知らせ】Twitter API有料化への対応</h3>
<ul>
  <li>2023年2月9日以降、Twitter API有料化に伴い、本サービスの提供を終了する可能性が高いです。
  <li>詳細は、<a href="https://github.com/aoirint/nalypoll/issues/7">GitHub Issue #7</a>をご確認ください。
  <li>ご利用ありがとうございました。
</ul>

<hr>

<h3>このアプリケーションで何ができますか？</h3>
<ul>
  <li>あなたは自分が投稿した投票ツイートをこのサービスに登録することで、投票状況の時系列変化を確認できるようになります。
  <li>鍵アカウントにはまだ対応していません。
</ul>

<h3>このアプリケーションは何をしますか？</h3>
<ul>
  <li>Twitterでログインすると、あなたが投稿した最近のツイートを10件まで取得し、そのうち投票が含まれるツイートを一覧表示します。
  <li>あなたは新しい投票ツイートをしたあと、一覧を表示してツイートをサービスに登録することができます。
  <ul>
    <li>すでに終了した投票ツイートは登録できません。
  </ul>
  <li>このアプリケーションは、あなたが登録したツイートの投票状況や周辺情報を適当な間隔ごとに自動取得し、記録します。
  <li>登録したツイートには個別ページを作り、投票状況の時系列変化をグラフで表示します。
  <li>削除されたツイートは自動更新のタイミングでこのサービス上から削除します。
</ul>

<h3>アプリケーションの使用をやめたいのですが？</h3>
<ul>
  <li>ログイン中に表示されるメニューという項目から、次の操作ができます。
  <li>ツイートの登録をすべて解除
    <ul>
      <li>あなたがサービス上に登録したツイートの登録をすべて解除します。
      <li>投票状況の自動更新は止まりますが、個別ページは削除されません。
    </ul>
  <li>投票状況関連データを削除
    <ul>
      <li>このサービス上に記録した、あなたにひもづいた投票状況に関連するデータを削除します。
      <li>ツイートの登録をすべて解除し、登録したツイートの投票状況ログ、個別ページを削除します。
    </ul>
  <li>認証情報の削除
    <ul>
      <li>あなたのログイン状態を保持している認証情報を削除します。
      <li>再ログインすることで新しい認証情報が記録されます。
    </ul>
</ul>

<h3>プライバシーポリシー</h3>
<ul>
  <li>
    このサービスの利用者から入手した情報は
    このサービスの提供や改善のためのみに使用し、
    許可なく他の用途に使用しません。
    ただし、例外として広報や分析等のためプライバシーに配慮した上で統計的な利用をすることがあります。
  <li>
    このサービスを利用する自身の情報に関する問い合わせは、
    開発者にこのサービスを利用しているTwitterアカウントを通じて行ってください。
</ul>

<h3>開発者</h3>
<ul>
  <li><a href="https://twitter.com/aoirint" target="_blank">@aoirint</a>
</ul>

<h3>その他</h3>
<ul>
  <li>アクセス状況の計測のためGoogle Analyticsを利用しています。
</ul>

{% endblock %}

Nalypoll/templates/me.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}マイページ - Nalypoll{% endblock %}

{% block main %}
<h2 class="mt-4">最近の投票ツイート</h2>

<div class="row">
{% for tweet in tweets %}
{% if tweet.attachments.poll_ids %}
  <div class="col-12 col-md-6 col-lg-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <a href="https://twitter.com/{{ tweet.author.username }}/status/{{ tweet.id }}" target="_blank">
            {{ tweet.text }}
          </a>
        </h5>
        <h6 class="small text-secondary mb-3">{{ tweet.author.name }} (@{{ tweet.author.username }})</h6>
{% for poll in tweet.polls %}
        <ul class="list-group my-4">
{% for option in poll.options %}
          <li class="list-group-item">{{ option.label }} ({{ option.votes }}票, {{ option.percentage |floatformat:-2 }}%)
{% endfor %}
        </ul>

        <div class="d-flex justify-content-end">
{% if tweet.can_register %}
          <form method="POST" action="{% url 'main:register_poll' tweet.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary px-4">登録</button>
          </form>
{% endif %}
{% if tweet.poll_data_on_service %}
          <a href="{% url 'main:poll' tweet.id %}" class="btn btn-secondary ml-4 px-4">確認</a>
{% endif %}
        </div>
{% endfor %}

      </div>
    </div>
  </div>
{% endif %}
{% endfor %}

  <div class="col-12 my-4 d-flex justify-content-end">
    <form method="POST" action="{% url 'main:register_poll' %}">
      {% csrf_token %}
      <div class="input-group">
        <input name="tweet_id" placeholder="Tweet ID" size="30">
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary px-4">登録</button>
        </div>
      </div>
    </form>
  </div>

</div>

{% endblock %}

Nalypoll/templates/menu.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}メニュー - Nalypoll{% endblock %}

{% block main %}

<h2 class="mt-4">メニュー</h2>
<div class="row">
  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:remove_user_polls' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">投票状況ログデータをサービスから削除</button> （過去の投票状況を見ることができなくなります）
    </form>
  </div>

  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:oauth_remove' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">認証情報をサービスから削除</button> （自動取得が停止します）
    </form>
  </div>

</div>

{% endblock %}

Nalypoll/templates/user.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}マイページ - Nalypoll{% endblock %}

{% block main %}

<div class="row">
  <div class="col-12 my-4 d-flex justify-content-end">
    <form method="POST" action="{% url 'main:register_poll' %}">
      {% csrf_token %}
      <div class="d-flex align-items-center">
        <label for="id_tweet_id_or_url" style="margin: 0 .5rem; white-space: nowrap;">新しいツイート</label>
        <div class="input-group">
          <input id="id_tweet_id_or_url" name="tweet_id_or_url" placeholder="Tweet ID or URL" size="30" class="form-control">
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary px-4">登録</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="col-12 d-flex justify-content-end">
    <a href="{% url 'main:user_recent' %}" class="btn btn-primary">最近のツイートから登録</a>
  </div>
</div>

<h2 class="mt-4">登録した投票ツイート</h2>
<div class="row">
{% for tweet in registering_tweets %}
{% include 'parts/tweet_card_db.html' %}
{% endfor %}
</div>

{% comment %}
<h2 class="mt-4">終了した投票ツイート</h2>

<div class="row">
{% for tweet in closed_poll_tweets %}
{% include 'parts/tweet_card_db.html' %}
{% endfor %}
</div>
{% endcomment %}

{% endblock %}

Nalypoll/templates/user_menu.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}メニュー - Nalypoll{% endblock %}

{% block main %}

<h2 class="mt-4">メニュー</h2>
<div class="row">
  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:user_unregister_polls' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">すべてのツイートの登録を解除</button> （投票状況の自動更新が停止します）
    </form>
  </div>

  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:user_remove_polls' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">投票状況ログデータをサービスから削除</button> （過去の投票状況を見ることができなくなります）
    </form>
  </div>

  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:oauth_remove' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">認証情報をサービスから削除</button>
    </form>
  </div>

</div>

{% endblock %}

Nalypoll/templates/user_recent.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}最近の投票ツイート - Nalypoll{% endblock %}

{% block main %}

<div class="row">
  <div class="col-12 my-4 d-flex justify-content-end">
    <form method="POST" action="{% url 'main:register_poll' %}">
      {% csrf_token %}
      <div class="d-flex align-items-center">
        <label for="id_tweet_id_or_url" style="margin: 0 .5rem; white-space: nowrap;">新しいツイート</label>
        <div class="input-group">
          <input id="id_tweet_id_or_url" name="tweet_id_or_url" placeholder="Tweet ID or URL" size="30" class="form-control">
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary px-4">登録</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="col-12 d-flex justify-content-end">
    <a href="{% url 'main:user' %}" class="btn btn-secondary">登録したツイートを確認</a>
  </div>
</div>

<h2 class="mt-4">最近の投票ツイート</h2>

<div class="row">
{% for tweet in tweets %}
{% include 'parts/tweet_card_api.html' %}
{% endfor %}

</div>

{% endblock %}