TwiAnalyPolls/TwiAnalyPolls/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('main.urls', namespace='main'))
    # path('admin/', admin.site.urls),
]

TwiAnalyPolls/apps/main/urls.py
from django.urls import path, include, re_path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('poll/<int:tweet_id>', views.poll, name='poll'),
    # path('update/<int:tweet_id>', views.update, name='update'),
    path('me', views.me, name='me'),
    path('menu', views.menu, name='menu'),
    path('menu/remove_user_polls', views.remove_user_polls, name='remove_user_polls'),
    path('oauth', views.oauth, name='oauth'),
    path('oauth/callback', views.oauth_callback, name='oauth_callback'),
    path('oauth/remove', views.oauth_remove, name='oauth_remove'),
    path('oauth/logout', views.oauth_logout, name='oauth_logout'),
]

TwiAnalyPolls/templates/base.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">

<title>{% block pagetitle %}{% endblock %}</title>

<link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
  crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
  crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"
  integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI="
  crossorigin="anonymous"></script>

<!-- https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/set-up-twitter-for-websites -->
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>


<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main:index' %}">TwiAnalyPolls</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
{% if twitter.is_authenticated %}
      <li class="nav-item">
        <a href="{% url 'main:me' %}" class="nav-link">マイページ</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'main:menu' %}" class="nav-link">メニュー</a>
      </li>
{% endif %}
    </ul>
    <ul class="navbar-nav">
{% if twitter.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">
        ログイン中（<a href="https://twitter.com/{{ twitter.screen_name }}" target="_blank">@{{ twitter.screen_name }}</a>）
        </span>
      </li>
      <li class="nav-item">
        <form method="POST" action="{% url 'main:oauth_logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn nav-link">ログアウト</button>
        </form>
      </li>
{% endif %}
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

TwiAnalyPolls/templates/index.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}TwiAnalyPolls{% endblock %}

{% block main %}
<h2 class="mt-4">TwiAnalyPolls</h2>

<p>
  <form method="POST" action="{% url 'main:oauth' %}">
    {% csrf_token %}
    <button type="submit" class="btn">
      <img src="{% static 'images/auth_twitter.png' %}" alt="Sign in with Twitter">
    </button>
  </form>

<hr>

<h3>このアプリケーションで何ができますか？</h3>
<ul>
  <li>あなたは自分が投稿した投票ツイートをこのサービスに登録することで、投票状況の時系列変化を確認できるようになります。
</ul>

<h3>このアプリケーションは何をしますか？</h3>
<ul>
  <li>Twitterでログインすると、あなたが投稿した最近のツイートを10件まで取得し、そのうち投票が含まれるツイートを一覧表示します。
  <li>あなたは新しい投票ツイートをしたあと、一覧を表示してツイートをサービスに登録することができます。
  <li>このアプリケーションは、あなたが登録したツイートの投票状況や周辺情報を適当な間隔ごとに自動取得し、記録します。
  <li>登録したツイートには個別ページを作り、投票状況の時系列変化をグラフで可視化します。
  <li>削除されたツイートは自動更新のタイミングでこのサービス上から削除します。
  <li>非公開になったアカウントのツイートは自動更新のタイミングで閲覧不能にします。
</ul>

<h3>アプリケーションの使用をやめたいのですが？</h3>
<ul>
  <li>ログイン中に表示されるメニューという項目から、次の操作ができます。
  <li>TODO: ツイートの登録をすべて解除
    <ul>
      <li>あなたがサービス上に登録したツイートの登録をすべて解除します。
      <li>投票状況の自動更新は止まりますが、個別ページは削除されません。
    </ul>
  <li>投票状況関連データを削除
    <ul>
      <li>このサービス上に記録した、あなたにひもづいた投票状況に関連するデータを削除します。
      <li>ツイートの登録をすべて解除し、登録したツイートの投票状況ログ、個別ページを削除します。
    </ul>
  <li>認証情報の削除
    <ul>
      <li>あなたのログイン状態を保持している認証情報を削除します。
      <li>再ログインすることで新しい認証情報が記録されます。
    </ul>
</ul>

{% endblock %}

TwiAnalyPolls/templates/me.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}マイページ - TwiAnalyPolls{% endblock %}

{% block main %}
<h2 class="mt-4">最近の投票ツイート</h2>

<form id="register_form" method="POST">
  {% csrf_token %}
  <input id="tweet_id_input" name="tweet_id" type="hidden">
</form>

<div class="row">
{% for tweet in tweets %}
{% if tweet.attachments.poll_ids %}
  <div class="col-12 col-md-6 col-lg-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <a href="https://twitter.com/{{ tweet.author.username }}/status/{{ tweet.id }}" target="_blank">
            {{ tweet.text }}
          </a>
        </h5>
        <h6 class="small text-secondary mb-3">{{ tweet.author.name }} (@{{ tweet.author.username }})</h6>
{% for poll in tweet.polls %}
        <ul class="list-group my-4">
{% for option in poll.options %}
          <li class="list-group-item">{{ option.label }} ({{ option.votes }}票, {{ option.percentage |floatformat:-2 }}%)
{% endfor %}
        </ul>

        <div class="text-right">
{% if not tweet.registered %}
          <button type="submit" data-tweet="{{ tweet.id }}" form="register_form" class="btn btn-primary register-tweet-button px-4">登録</button>
{% else %}
          <a href="{% url 'main:poll' tweet.id %}" class="btn btn-secondary px-4">確認</a>
{% endif %}
        </div>
{% endfor %}

      </div>
    </div>
  </div>
{% endif %}
{% endfor %}
</div>

<script>
(function() {
  let tweetIdInput = document.querySelector('#tweet_id_input');
  [...document.querySelectorAll('.register-tweet-button')].forEach(button => {
    button.addEventListener('click', event => {
      tweetIdInput.value = button.dataset.tweet;
    });
  });
})();
</script>

{% endblock %}

TwiAnalyPolls/templates/menu.html
{% extends 'base_basic.html' %}
{% load static %}

{% block pagetitle %}メニュー - TwiAnalyPolls{% endblock %}

{% block main %}

<h2 class="mt-4">メニュー</h2>
<div class="row">
  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:remove_user_polls' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">投票状況関連データをサービスから削除</button> （過去の投票状況ログを削除します）
    </form>
  </div>

  <div class="col-12 my-4">
    <form method="POST" action="{% url 'main:oauth_remove' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">認証情報をサービスから削除</button> （自動取得が停止します）
    </form>
  </div>

</div>

{% endblock %}

TwiAnalyPolls/templates/poll.html
{% extends 'base_fluid.html' %}

{% block pagetitle %}{{ tweet.author.name }} (@{{ tweet.author.screen_name }}) さんの投票ツイート: {{ tweet.text_oneline |truncatechars:40}} - TwiAnalyPolls{% endblock %}

{% block main %}
<div class="pt-4"></div>

<div id="data_polls"
  data-tweet="{{ tweet.json }}"
  data-polls="{{ tweet.polls_json }}"
></div>


<div class="row mx-lg-5">
  <div class="col-12 col-lg-4">
    <div class="row h-100">
      <div class="col-12">
{% if tweet.last_polls.first.voting_status == 'open' %}
        <div class="alert alert-primary">
          投票受付中
        </div>
{% else %}
        <div class="alert alert-success">
          投票終了
        </div>
{% endif %}
      </div>
      <div class="col-12">
        <div id="embed_tweet_container" class="d-flex justify-content-center align-items-center"></div>
      </div>
    </div>
  </div>

  <div id="chart_polls" class="my-4 py-4 col-12 col-lg-8"></div>
</div>

<script>
(function() {
  function timestampSeconds2label(timestampSeconds) {
    let de = new Date(timestampSeconds * 1000);
    let h = new String(de.getHours());
    if (h.length == 1) h = '0' + h;

    let m = new String(de.getMinutes());
    if (m.length == 1) m = '0' + m;

    return h + ':' + m;
  }

  let dataPollsElm = document.querySelector('#data_polls');
  let tweet = JSON.parse(dataPollsElm.dataset.tweet);
  let polls = JSON.parse(dataPollsElm.dataset.polls);

  let embedTweetContainer = document.querySelector('#embed_tweet_container');
  twttr.ready(twttr => {
    twttr.widgets.createTweet(tweet.id, embedTweetContainer, {
    }).then(elm => {
    });
  });

  let chartPollsElm = document.querySelector('#chart_polls');

  for (let poll of polls) {
    let chartPollElm = document.createElement('canvas');
    chartPollElm.width = 1600;
    chartPollElm.height = 900;
    chartPollsElm.appendChild(chartPollElm);

    let chartPollCtx = chartPollElm.getContext('2d');

    let options = Object.keys(poll.votes);
    let timestamps = poll.timestamps;
    let datasets = [];
    let backgroundColors = [
      'rgba(255, 99, 132, 0.2)',
      'rgba(54, 162, 235, 0.2)',
      'rgba(255, 206, 86, 0.2)',
      'rgba(75, 192, 192, 0.2)',
    ];
    let borderColors = [
      'rgba(255, 99, 132, 1)',
      'rgba(54, 162, 235, 1)',
      'rgba(255, 206, 86, 1)',
      'rgba(75, 192, 192, 1)',
    ];

    let sampleCount = poll.votes[options[0]].length;
    for (let optionIndex in options) {
      let option = options[optionIndex];
      let votesList = poll.votes[option];
      let data = [];

      data.push({
        'x': tweet.posted_at,
        'y': 0,
      });

      for (let votesIndex in votesList) {
        let time = timestamps[votesIndex];
        if (time > poll.end_time) continue;
        data.push({
          'x': time,
          'y': votesList[votesIndex],
        })
      }

      // closed => last votes == final result
      if (poll.voting_status == 'closed' && votesList.length > 0) {
        data.push({
          'x': poll.end_time,
          'y': votesList[votesList.length - 1],
        });
      }

      datasets.push({
        'label': option,
        'data': data,
        'backgroundColor': backgroundColors[optionIndex],
        'borderColor': borderColors[optionIndex],
        'borderWidth': 1,
      })
    }

    let chartPoll = new Chart(chartPollCtx, {
      'type': 'line',
      'data': {
        'datasets': datasets,
      },
      'options': {
        'scales': {
          'xAxes': [{
            'type': 'linear',
            'position': 'bottom',
            'ticks': {
              'autoSkip': true,
              'maxRotation': 90,
              'minRotation': 90,
              'min': tweet.posted_at,
              'max': poll.end_time,
              'callback': (value, index, values) => {
                return timestampSeconds2label(value);
              },
            },
          }],
          'yAxes': [{
            'ticks': {
              'min': 0,
              'precision': 0,
            },
          }],
        },
        'tooltips': {
          'mode': 'index',
          'intersect': false,
          'itemSort': (a, b, data) => b.yLabel - a.yLabel,
          'callbacks': {
            'title': (tooltipItems, data) => {
              let timestamp = parseInt(tooltipItems[0].xLabel); // original label
              let title = timestampSeconds2label(timestamp);

              return title;
            },
          },
        },
        'hover': {
          'mode': 'index',
          'intersect': false,
        }
      },
    });

    break;
  }

})();
</script>

{% endblock %}